// filepath: /media/tkk/Daten/dev/Projekte/dokus/linux/docker/nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
    
    include /etc/nginx/sites-enabled/*;
}